// Generated by scripts/write-theme-ids.ts from @deckard/themes. Do not edit.
//
// Committed, unlike the other generated files here, because typecheck and the
// unit tests read it without building the CLI first. Regenerate with pnpm build
// in packages/cli; theme-source.test.ts fails while this is behind.
import type { BuiltInThemeId } from "@deckard/themes/ids"

export const themeIds = [
  "aurora",
  "ledger",
  "meridian",
  "nexus",
  "phosphor",
] as const satisfies readonly BuiltInThemeId[]

export const defaultThemeId: BuiltInThemeId = "meridian"
