#!/usr/bin/env node
import fs from "node:fs"
import path from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"

import { defaultThemeId, themeIds } from "../../themes/src/ids.ts"

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  ".."
)
const target = path.join(packageRoot, "src/deck/built-in-themes.ts")

// Read straight from the theme package's source rather than its dist, so this
// runs before anything is built: prepack calls it on a clean checkout.
function module(): string {
  return `// Generated by scripts/write-theme-ids.ts from @thebuilder/deckard-themes. Do not edit.
//
// Committed, unlike the other generated files here, because typecheck and the
// unit tests read it without building the CLI first. Regenerate with pnpm build
// in packages/cli; theme-source.test.ts fails while this is behind.
import type { BuiltInThemeId } from "@thebuilder/deckard-themes/ids"

export const themeIds = [
${themeIds.map((id) => `  "${id}",`).join("\n")}
] as const satisfies readonly BuiltInThemeId[]

export const defaultThemeId: BuiltInThemeId = "${defaultThemeId}"
`
}

export function writeThemeIds(): boolean {
  const contents = module()
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null

  if (current === contents) {
    return false
  }

  fs.writeFileSync(target, contents)

  return true
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const rewritten = writeThemeIds()

  process.stdout.write(
    `built-in themes ${rewritten ? "rewritten" : "already current"} (${themeIds.length} names)\n`
  )
}
